// API_URL = "https://aqi-predictor-831q.onrender.com/predict"
MONGODB_URI = "mongodb+srv://areesha_fatima:data123@cluster0.jhsvhd5.mongodb.net/?appName=Cluster0"
DB_NAME = "aqi_db"
FEATURE_COLLECTION = "aqi_features"
MODEL_REGISTRY_COLLECTION = "model_registry"
